version: "3.8"

services:
  ingestion_service:
    build:
      context: ../ingestion_service
    ports:
      - "8001:8001"
    volumes:
      - ../ingestion_service:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ../ingestion_service
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ../ingestion_service:/app
    environment:
      - PYTHONPATH=/app
