
services:
  api_gateway:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/reports_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../:/app
    command: uvicorn api_gateway.main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reports_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
