services:
  ingestion_service:
    build:
      context: ../ingestion_service
    ports:
      - "8000:8000"
    volumes:
      - ../ingestion_service:/app
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  celery_worker:
    build:
      context: ../ingestion_service
    command: celery -A tasks worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ../ingestion_service:/app
    environment:
      - PYTHONPATH=/app
